use_frameworks!

target 'AlgebraFx_Example' do
  pod 'AlgebraFx/RxCocoa', :path => '../'

  target 'AlgebraFx_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2'
    pod 'Nimble', '~> 7.0'
  end
end
